export const USER_INFO_UPDATE_SUCCESS = 'USER_INFO_UPDATE_SUCCESS';
export const FETCH_USER_SUCCESS = 'FETCH_USER_SUCCESS';

export const LOGIN_FACEBOOK_REQUEST = 'LOGIN_FACEBOOK_REQUEST';
export const LOGIN_FACEBOOK_SUCCESS = 'LOGIN_FACEBOOK_SUCCESS';
export const LOGIN_FACEBOOK_ERROR = 'LOGIN_FACEBOOK_ERROR';

export const USER_MATCH_UPDATE_SUCCESS = 'USER_MATCH_UPDATE_SUCCESS';
export const GET_ANOTHER_USER_SUCCESS = 'GET_ANOTHER_USER_SUCCESS';
export const GET_MATCHES_SUCCESS= 'GET_MATCHES_SUCCESS';

export const POSITIVE_MATCH = 'POSITIVE_MATCH';
export const NEGATIVE_MATCH = 'NEGATIVE_MATCH';
export const MUTUAL_MATCH = 'MUTUAL_MATCH';